name: Vert Vixen Cosplay
favicon: null
layout_spectrum: 0.9947
typography_spectrum: 0.20609
title: Vert VIxen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#061117'
    - '#4f3f5d'
    - '#afab9f'
    - '#920021'
    - '#e55970'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
