name: Vert Vixen Cosplay
favicon: null
layout_spectrum: 0.26205
typography_spectrum: 0.15033995220437646
title: Vert VIxen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#061117'
    - '#4f3f5d'
    - '#afab9f'
    - '#920021'
    - '#e55970'
  brandStrength: 0.5
  lightness: 0.5133131581824273
  saturation: 0.5056564307305962
  rhythmicContrast: 0.8897187081165612
purpose: []
